### ISSUE TITLE
"head: illegal line count" on MacOs

### ISSUE THREAD

**Issue by nitnelave** [Zepmann/lldap-cli#1]
It seems Mac's `head` is not as powerful as the one you're using.

Maybe we should detect mac and require `ghead` instead? See https://superuser.com/questions/543950/opposite-of-tail-all-lines-except-the-last-n-lines

**Comment by Zepmann** [comment]
LLDAP-CLI depends on GNU core utilities. While I might try to reduce this dependency at some point in the future, I will not make individual workarounds for other tools packages that implement a subset of its features. Since both [brew](https://formulae.brew.sh/formula/coreutils) and [MacPorts](https://ports.macports.org/port/coreutils/details/) provide coreutils, it might be easy for an admin to add support for this themselves by making coreutils the default. I don't use MacOS, so maybe you can do some testing for me.

If using brew, run before running LLDAP-CLI:
```
PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"
```

If using MacPorts, run before running LLDAP-CLI:
```
PATH="${prefix}/libexec/gnubin/:$PATH"
```
Where ${prefix} is your MacPorts prefix (`/opt/local` by default).

Note that this is documented on the brew and MacPorts coreutils package pages.

**Comment by nitnelave** [comment]
Finally found time to test it, and it works. Thanks!
