### ISSUE TITLE
Unable to change the password of an user

### ISSUE THREAD

**Issue by ldidry** [Zepmann/lldap-cli#5]
When trying to change the password of a user with the following command:
```bash
lldap-cli user update set foobar password bazqux
```
I get the following error:
```
/usr/sbin/lldap-cli: ligne 790: lldap_set_password : commande introuvable
```

**Comment by Zepmann** [comment]
As README.md states:

> Furthermore, `lldap_set_password` is neccessary to set user passwords.

The password cannot be changed using the GraphQL API. `lldap_set_password` is a separate executable from the LLDAP project to build and install for this specific purpose.

It is also possible to change the password using an LDAP client (such as `ldappasswd` from OpenLDAP), but I removed support for this from an earlier version since it just adds more complexity without having any real benefit. It also subverts one of the security design ideas of LLDAP.

I could in theory use any (non-GraphQL) web API calls to change the password or maybe inject it into the web form, but LLDAP relies on client-side hashing of the new password if passwords are changed through the web interface. LLDAP-CLI would need to rely on some other tools (which include Argon2 support) to do this. Again, much more complex than relying on an executable that should be included with LLDAP anyway.

**Comment by ldidry** [comment]
> Furthermore, lldap_set_password is neccessary to set user passwords.

Damn! Sorry about the issue.

**Comment by Zepmann** [comment]
No problem. :+1: , @ldidry!

**Comment by git529** [comment]
Hi. Can you please explain how can I change a user's password using the lldap-cli script? My lldap server is remote and when I tried running the script on my local machine i get `/usr/local/bin/lldap-cli: line 682: lldap_set_password: command not found`

I do see the `lldap_set_password` executable exists in the `/app` directory inside the lldap docker container which runs on the remote server

**Comment by Zepmann** [comment]
@git529 

> I tried running the script on my local machine i get `/usr/local/bin/lldap-cli: line 682: lldap_set_password: command not found`

Well, there is the problem. You run LLDAP-CLI on your local machine, and the error states that `lldap_set_password` is not found on your local machine.

Ideally you would install LLDAP locally through your distribution's package manager. An alternative is getting the compiled binaries for your local client architecture [straight from LLDAP](https://github.com/lldap/lldap/releases), extracting them and putting `lldap_set_password` in a path where it can be found (such as `/usr/local/bin`).

**Comment by git529** [comment]
> Ideally you would install LLDAP locally through your distribution's package manager.

Thank you @Zepmann !! Perhaps it would be a good idea to add the following info to your README.

I had already tried installing the `lldap` package in my local machine through my distribution's package manager (in my case Ubuntu 20.04 amd64) which failed since the `lldap` package is not available in standard Ubuntu repositories. 

Thanks to your reply, I searched more thoroughly and stumbled upon [this page](https://lib.rs/crates/lldap_auth#readme-from-a-package-repository) which says the package (for Ubuntu and all other Linux distributions) is actually available here → "[Unofficial Debian support is offered through the openSUSE Build Service](https://lib.rs/crates/lldap_auth#readme-from-a-package-repository#:~:text=Unofficial%20Ubuntu%20support%20is%20offered%20through%20the%20openSUSE%20Build%20Service")":

> <details open="">
> <summary><b>Ubuntu</b></summary>
> <br>
> Unofficial Ubuntu support is offered through the <a href="https://build.opensuse.org/" rel="noopener ugc nofollow">openSUSE Build Service</a>.<br><br>
> Maintainer: <a href="https://github.com/Masgalor" rel="noopener ugc nofollow">@Masgalor</a><br>
> Support: <a href="https://codeberg.org/Masgalor/LLDAP-Packaging/issues" rel="noopener ugc nofollow">Codeberg</a>, <a href="https://github.com/lldap/lldap/discussions" rel="noopener ugc nofollow">Discussions</a><br>
> Package repository: <a href="https://software.opensuse.org//download.html?project=home%3AMasgalor%3ALLDAP&amp;package=lldap" rel="noopener ugc nofollow">SUSE openBuildService</a><br>
> <table>
> <tbody><tr>
> <td>Available packages:</td>
> <td>lldap</td>
> <td>Light LDAP server for authentication.</td>
> </tr>
> <tr>
> <td></td>
> <td>lldap-extras</td>
> <td>Meta-Package for LLDAP and its tools and extensions.</td>
> </tr>
> <tr>
> <td></td>
> <td>lldap-migration-tool</td>
> <td>CLI migration tool to go from OpenLDAP to LLDAP.</td>
> </tr>
> <tr>
> <td></td>
> <td>lldap-set-password</td>
> <td>CLI tool to set a user password in LLDAP.</td>
> </tr>
> <tr>
> <td></td>
> <td>lldap-cli</td>
> <td>LLDAP-CLI is an unofficial command line interface for LLDAP.</td>
> </tr>
> </tbody></table>
> LLDAP configuration file: /etc/lldap/lldap_config.toml<br>
> </details>

So, I added the repo to my sources and simply did `sudo apt update && sudo apt install -y lldap-set-password` which installed the `lldap_set_password` binary in my path, and then I was able to use the `lldap-cli` command to add new user with password (I had previously installed the `lldap-cli` package differently, but for others wondering, it can also be installed from the [opensuse repo](https://software.opensuse.org//download.html?project=home%3AMasgalor%3ALLDAP&package=lldap) as detailed above):
```
ubuntu@remoteserver ~ $ lldap-cli -t 'escaped token here' -H 'https://ldap.example.com:443' user add test.user test.user@example.com -p 'escaped new user password here' -d 'Test User' -f Test -l User

Created user: test.user
Successfully changed test.user's password
```

Thanks again.

**Comment by Zepmann** [comment]
@git529 

As the developer(s) of LLDAP do(es) for LLDAP, I will not support third-party packaging of LLDAP-CLI. Like most small projects, the effort required to maintain and support packages will be left to others (i.e. the community).

I am happy to consider pull requests that offer an installation section for the documentation. In it, package repositories can be mentioned in a manner similar to [LLDAP's documentation](https://github.com/lldap/lldap/blob/main/docs/install.md/#from-a-package-repository). Do note that a similar warning must be included:

```
Do not open issues in this repository for problems with third-party pre-built packages. Report issues downstream.
```
